[alias]
frontend-build = ["run", "-p", "frontend-runner", "--", "build-debug"]
frontend-release = ["run", "-p", "frontend-runner", "--", "build-release"]
gui-build = ["run", "-p", "frontend-runner", "--", "gui-build"]
gui-build-debug = ["run", "-p", "frontend-runner", "--", "gui-build-debug"]
gui-dev = ["run", "-p", "frontend-runner", "--", "gui-dev"]
cli-release = ["run", "-p", "frontend-runner", "--", "cli-release"]
cli-deploy = ["run", "-p", "frontend-runner", "--", "cli-deploy"]
cli-run = ["run", "-p", "rconv", "--"]
cli-run-release = ["run", "--release", "-p", "rconv", "--"]
curator-snapshot-dev = ["run", "-p", "curator_snapshot"]
