name: Update Curated Model Snapshot

on:
  schedule:
    - cron: "0 8 1,15 * *"
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Build curated snapshot
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          AA_API_KEY: ${{ secrets.AA_API_KEY }}
        run: cargo run -p curator_snapshot -- --out static/model_snapshot.json --aliases static/aliases.json

      - name: Commit snapshot updates
        run: |
          if git diff --quiet static/model_snapshot.json; then
            echo "No snapshot changes detected."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add static/model_snapshot.json
          git commit -m "chore: refresh curated model snapshot"
          git push
